WIP: Feature/highlight rightclicked node
VerWiki/VerWikiApp pull request #14
Opened 2021-03-01 14:08 UTC by slakh96

Completes https://github.com/orgs/VerWiki/projects/1#card-55832022

2021-03-22 01:01 UTC, rafiiary requested changes

2021-03-22 01:01 UTC, rafiiary commented on frontend/src/components/Tree/Tree.jsx
> +      } else if (d.data.numChildren === 0) {
Why is this variable name simply "d"? I know this comes from a previous MR but the name doesn't tell me much about what the variable is. Is there a reason or can we find a more informative name?

2021-03-22 01:01 UTC, rafiiary commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
Let's remove the else clause and just return #555

2021-03-22 01:01 UTC, rafiiary commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
Same thing with the else clause here

2021-03-22 01:01 UTC, rafiiary commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
Same thing here

2021-03-22 01:01 UTC, rafiiary commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
Here too please :)

2021-03-24 10:31 UTC, slakh96 commented on frontend/src/components/Tree/Tree.jsx
> +      } else if (d.data.numChildren === 0) {
name changed

2021-03-24 10:32 UTC, slakh96 commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
removed

2021-03-24 10:32 UTC, slakh96 commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
removed

2021-03-24 10:32 UTC, slakh96 commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
removed

2021-03-24 10:32 UTC, slakh96 commented on frontend/src/components/Tree/Tree.jsx
> +      } else {
removed

2021-03-25 03:14 UTC, rafiiary approved these changes

2021-03-26 22:36 UTC, merged