Feature/improved show distant tree
VerWiki/VerWikiApp pull request #20
Opened 2021-03-17 01:40 UTC by sultansidhu

2021-03-22 02:55 UTC, rafiiary requested changes

2021-03-22 02:55 UTC, rafiiary commented on frontend/src/components/TreeViewer/TreeViewer.jsx
> +  } else {
Remove the else clause please :)

2021-03-24 10:49 UTC, slakh96 commented on frontend/src/components/TreeViewer/TreeViewer.jsx
> +  } else {
fixed

2021-03-25 03:17 UTC, rafiiary approved these changes

2021-03-27 00:53 UTC, merged